# Generated by Django 4.1.7 on 2023-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(max_length=400, upload_to='pics'),
        ),
    ]
