# Generated by Django 4.1.7 on 2023-03-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo3app', '0003_team_alter_place_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Team_members',
        ),
    ]
