# Generated by Django 4.1.7 on 2023-03-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo3app', '0004_rename_team_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_members',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='team_members',
            old_name='img',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='team_members',
            old_name='name',
            new_name='name2',
        ),
    ]
