# Generated by Django 4.1.7 on 2023-03-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo3app', '0005_rename_desc_team_members_desc2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_members',
            new_name='Team_memberss',
        ),
    ]
