# Generated by Django 4.1.7 on 2023-03-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo3app', '0006_rename_team_members_team_memberss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_memberss',
            new_name='Members',
        ),
    ]
